version: '3.8'
services:
  postgres:
    image: 'postgres'
    container_name: general
    environment:
      - POSTGRES_USER=${POSTGRES_GENERAL_USER}
      - POSTGRES_PASSWORD=${POSTGRES_GENERAL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_GENERAL_DB}
      - PGPORT=${POSTGRES_GENERAL_PORT}
    ports:
      - '${POSTGRES_GENERAL_PORT}:${POSTGRES_GENERAL_PORT}'
    volumes:
      - general_data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_GENERAL_PORT}
    networks:
      - shared_network

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
    name: shared_network

volumes:
  general_data:
  redis_data:
