version: '3.8'
services:
  api-pure-blog:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.api-pure-blog
      args:
        DATABASE_GENERAL_URL: ${DATABASE_GENERAL_URL}
        DATABASE_MARKETING_URL: ${DATABASE_GENERAL_URL}
    ports:
      - '${NX_PUBLIC_BACK_PURE_BLOG}:${NX_PUBLIC_BACK_PURE_BLOG}'
    environment:
      - NODE_ENV=production
    networks:
      - shared_network
    env_file:
      - .env

networks:
  shared_network:
    external: true
