version: '3.8'
services:
  server-general:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.server-pure-general
    ports:
      - '${SERVER_PURE_GENERAL_PORT}:${SERVER_PURE_GENERAL_PORT}'
    environment:
      - NODE_ENV=production
    networks:
      - shared_network
    env_file:
      - .env
  web-pure-digital:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.web-pure-digital
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - shared_network
    env_file:
      - .env

networks:
  shared_network:
    external: true
