FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build:a-web-pure-digital

FROM nginx:alpine as runner

COPY --from=builder /app/dist/apps/web/angular/a-web-pure-digital /usr/share/nginx/html
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
