FROM node:20.19-slim AS builder

WORKDIR /app

COPY . .

RUN npm install


RUN npm run build:web-pure-digital

FROM node:20.19-slim AS runner

WORKDIR /app

COPY --from=builder /app/apps/web/web-pure-digital/.next .next
COPY --from=builder /app/apps/web/web-pure-digital/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

EXPOSE 3000
ENV NODE_ENV=production

CMD ["npx", "next", "start"]
